### ISSUE TITLE
Generator failure

### ISSUE THREAD

**Issue by dflynn15** [ethanmuller/generator-mg-redux#8]
Currently the generator does not work when trying to start a new project with Pattern Lab. 

When
`yo mg-redux`

Regardless of choosing pattern lab or not you get the following output immediately after your pattern lab choice:

```
/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.all.js:8956
                throw e;
                      ^
Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/generator-mg-redux/app/templates/.gitignore'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at _prepCopy (/usr/local/lib/node_modules/generator-mg-redux/node_modules/yeoman-generator/lib/actions/actions.js:55:13)
    at copy (/usr/local/lib/node_modules/generator-mg-redux/node_modules/yeoman-generator/lib/actions/actions.js:83:19)
    at yeoman.generators.Base.extend.app (/usr/local/lib/node_modules/generator-mg-redux/app/index.js:62:10)
    at /usr/local/lib/node_modules/generator-mg-redux/node_modules/yeoman-generator/lib/base.js:341:43
    at /usr/local/lib/node_modules/generator-mg-redux/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
    at /usr/local/lib/node_modules/generator-mg-redux/node_modules/yeoman-generator/node_modules/async/lib/async.js:227:13
    at iterate (/usr/local/lib/node_modules/generator-mg-redux/node_modules/yeoman-generator/node_modules/async%
```

Could be missing a dependency?

**Comment by ethanmuller** [comment]
Hm, this doesn't occur when I use my locally linked NPM module, but it does when I use NPM's package.

Thanks for letting me know about this. Looking into it.

**Comment by ethanmuller** [comment]
Yup, seems to have done the trick. Fixed in 0.2.4. :+1:
